/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gs.rest.service.main.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
